### ISSUE TITLE
What software is needed to open the brd and sch file?

### ISSUE THREAD

**Issue by dproldan** [npiegdon/tms-rgb#1]
For board manufacturing,  three things are needed:  GERBER, BOM and CENTROID.
I couldn't find them anywhere and thought of extracting them from the provided files,  but Kicad fails and no indication of the software used to design this project is given.
 Which software did you use?  Thanks for your hard work and for sharing it!

**Comment by hanshuebner** [comment]
The board was designed with [Eagle](https://www.autodesk.com/products/eagle/free-download).  I've successfully generated Gerbers and ordered them from JLCPCB, but that was a long time ago and I don't have the files anymore.

**Comment by npiegdon** [comment]
Yep, it's an Eagle project.  (And KiCAD has a pretty good Eagle importer these days, now that you know what to look for.)

You can skip that step completely and just grab the zip with the pre-made Gerbers from the asset list on the [Releases](https://github.com/npiegdon/tms-rgb/releases) page.
